### ISSUE TITLE
[v9][UI UX] Payment request throws "Something could not be processed" message

### ISSUE THREAD

**Issue by sushantnadkar** [DigiThinkIT/authorizenet#32]
Steps to recreate:
1. Go to payment request link 
2. Enter reference number and proceed
3. Fill all the card details and click on `Submit Payment`

Expected behavior:
- Redirected to payment success page

Actual behavior:
- _Something could not be processed_ message appears but payment is accepted

Screenshot:
![image](https://user-images.githubusercontent.com/8912289/33927153-25a0e7d6-e007-11e7-891f-696c4420e7e5.png)

Stacktrace:
```
13:01:13 web.1            | Traceback (most recent call last):
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/authorizenet/authorizenet/authorizenet/doctype/authorizenet_settings/authorizenet_settings.py", line 540, in create_request
13:01:13 web.1            |     status)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 702, in run_method
13:01:13 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 965, in composer
13:01:13 web.1            |     return composed(self, method, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 948, in runner
13:01:13 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 696, in <lambda>
13:01:13 web.1            |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 207, in on_payment_authorized
13:01:13 web.1            |     self.run_method("set_as_paid")
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 702, in run_method
13:01:13 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 965, in composer
13:01:13 web.1            |     return composed(self, method, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 948, in runner
13:01:13 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 696, in <lambda>
13:01:13 web.1            |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 98, in set_as_paid
13:01:13 web.1            |     self.make_invoice()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py", line 59, in make_invoice
13:01:13 web.1            |     si.submit()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 778, in submit
13:01:13 web.1            |     self._submit()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 767, in _submit
13:01:13 web.1            |     self.save()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 256, in save
13:01:13 web.1            |     return self._save(*args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 307, in _save
13:01:13 web.1            |     self.run_post_save_methods()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 831, in run_post_save_methods
13:01:13 web.1            |     self.run_method("on_submit")
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 702, in run_method
13:01:13 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 965, in composer
13:01:13 web.1            |     return composed(self, method, *args, **kwargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/model/document.py", line 950, in runner
13:01:13 web.1            |     add_to_return_value(self, f(self, method, *args, **kwargs))
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/erpnext_taxjar/erpnext_taxjar/api.py", line 103, in create_transaction
13:01:13 web.1            |     frappe.throw(_(sanitize_error_response(err)))
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/__init__.py", line 319, in throw
13:01:13 web.1            |     msgprint(msg, raise_exception=exc, title=title, indicator='red')
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/__init__.py", line 309, in msgprint
13:01:13 web.1            |     _raise_exception()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
13:01:13 web.1            |     raise raise_exception(encode(msg))
13:01:13 web.1            | ValidationError: Something could not be processed
13:01:13 web.1            |
13:01:13 web.1            | Traceback (most recent call last):
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/app.py", line 57, in application
13:01:13 web.1            |     response = frappe.handler.handle()
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/handler.py", line 22, in handle
13:01:13 web.1            |     data = execute_cmd(cmd)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/handler.py", line 53, in execute_cmd
13:01:13 web.1            |     return frappe.call(method, **frappe.form_dict)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/frappe/frappe/__init__.py", line 935, in call
13:01:13 web.1            |     return fn(*args, **newargs)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/authorizenet/authorizenet/authorizenet/doctype/authorizenet_settings/authorizenet_settings.py", line 623, in process
13:01:13 web.1            |     data = frappe.get_doc("AuthorizeNet Settings").create_request(data)
13:01:13 web.1            |   File "/Users/sushantnadkar/workbench/frappe-benchv8/apps/authorizenet/authorizenet/authorizenet/doctype/authorizenet_settings/authorizenet_settings.py", line 545, in create_request
13:01:13 web.1            |     raise ex
13:01:13 web.1            | ValidationError: Something could not be processed

**Comment by Alchez** [comment]
So this error is being spawned by TaxJar when making a payment from a local development system.

It pings the TaxJar API, and finds an existing transaction for the reference document (Sales Invoice), which is why it breaks on trying to return the Sales Tax value, but lets the Authorizenet transaction go through anyway.

Valmik made a [fix](https://github.com/DigiThinkIT/erpnext_taxjar/pull/15) to prevent the system from pinging TaxJar to create transactions in testing environments.
